name: Docker Image CI

on:
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build
    - name: login docker hub
      run: echo "${{ secrets.ACCESS_TOKEN }}" | docker login -u zhouyixun --password-stdin
    - name: build docker image
      run: docker build -t sonicorg/sonic-client-web:v1.4.1-beta .
    - name: push docker image
      run: docker push sonicorg/sonic-client-web:v1.4.1-beta
    - name: login docker hub
      run: echo "${{ secrets.ACCESS_TOKEN_ALIYUN }}" | docker login --username=小虫哔哔 registry.cn-hangzhou.aliyuncs.com --password-stdin
    - name: tag
      run : docker tag sonicorg/sonic-client-web:v1.4.1-beta registry.cn-hangzhou.aliyuncs.com/sonic-cloud/sonic-client-web:v1.4.1-beta
    - name: push docker image
      run: docker push registry.cn-hangzhou.aliyuncs.com/sonic-cloud/sonic-client-web:v1.4.1-beta
